# Generated by Django 4.0 on 2021-12-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('questions', '0002_question_product_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_type_question', to='contenttypes.contenttype'),
        ),
    ]
